### PR TITLE
posix: Support partial reads from sockets

### PR DESCRIPTION
**Pull request by Dennisbonke**
Both for unix sockets and netlink sockets. Fixes dbus.

### CODE REVIEW

**Comment by qookei** [comment]
After thinking about this some more, I don't think this is actually truncation... (but this is still something we should do)

**Comment by qookei** [comment]
As in, this is correct, but leave the TODO comments, since truncation would mean that we do something else for datagram sockets.

**Comment by qookei** [comment]
Can you also reword the commits? I think the proper term we're looking for is partial reads.

**Comment by avdgrinten** [comment]
UNIX sockets support both stream semantics and packet semantics. We only implement stream semantics here (?). We should check which type of socket we're actually dealing with and maybe also implement packet semantics.

**Comment by qookei** [comment]
> UNIX sockets support both stream semantics and packet semantics. We only implement stream semantics here (?). We should check which type of socket we're actually dealing with and maybe also implement packet semantics.

That's true, I'm just pointing out this is implementing partial reads with stream semantics, not truncation with packet semantics.

**Comment by Dennisbonke** [comment]
Reworded as requested.

**Review by no92 — APPROVED** [review]
LGTM

**Review by no92 — APPROVED** [review]
LGTM

**Pull request merged**
