### PR TITLE
docs: Clarify braces usage in single line if, while, for loops

### PR DESCRIPTION
**Pull request by Dennisbonke**
Personally, it improves readability. I left it out in the initial version because the discussion about it was going nowhere. Let's reopen it!

### CODE REVIEW

**Comment by avdgrinten** [comment]
My opinion on this has not changed; I still dislike this.

What about adding `-Werror=misleading-indentation` instead of changing the style?

**Comment by Dennisbonke** [comment]
Personally, I'm in favor of both. Makes it really clear what is guarded behind the statement and avoids weird indentation that misleads people.

**Comment by avdgrinten** [comment]
Can you give an example where the indentation is confusing?

This arguably not confusing in general. Python doesn't use any braces and people can read Python just fine.

All else being equal, shorter code should be preferred, and additional braces increase the vertical space required to render the code.

**Comment by Dennisbonke** [comment]
This PR is obsolete based upon this line in the coding style.

```
Braces shall follow "K&R Bracing Style variant One True Bracing". The K&R Bracing Style was first introduced in The C Programming Language by Brian Kernighan and Dennis Ritchie.
```

I do agree with adding the `-Werror=misleading-indentation` flag to the compilation flags, I'll get to work on doing that in a separate PR.

**Pull request closed without merging**
