### PR TITLE
Small cleanups

### PR DESCRIPTION
**Pull request by no92**

### CODE REVIEW

**Review by Dennisbonke — COMMENTED** [review]
LGTM but what are all those empty lines that show up as changed in the diff?

**Comment by no92** [comment]
That's whitespace being trimmed.

**Comment by ArsenArsen** [comment]
would've been clear if there was a separate commit for it ;)

**Comment by no92** [comment]
Dropped the first commit as it's already merged, rebased on master and expanded the error handling as discussed on Discord.

**Review by ArsenArsen — APPROVED** [review]

**Pull request merged**
