### PR TITLE
nic: add support for Intel 82XX Gigabit Ethernet family

### PR DESCRIPTION
**Pull request by cleanbaja**
I am working on adding this family of well known and common Ethernet cards, and this pull request shows my progress in doing so.

### CODE REVIEW

**Comment by YusufKhan-improves-shit** [comment]
Hi! Reading the BSD driver I can see that it is quite portable. Couldnt this be out of tree with patches to e1000_osdep.c. etc?

Just a thought

**Comment by Dennisbonke** [comment]
> Hi! Reading the BSD driver I can see that it is quite portable. Couldnt this be out of tree with patches to e1000_osdep.c. etc?
> 
> Just a thought

Why would it be out of tree? We want these drivers in tree. So I don't see the usecase for that.

**Comment by YusufKhan-improves-shit** [comment]
> Why would it be out of tree? We want these drivers in tree. So I don't see the usecase for that.

The BSD driver is licensed under the BSD 3-clause license, which is not allowed as managarm is strictly MIT.

**Comment by ArsenArsen** [comment]
We can't really use an architecturally incompatible driver here. Wherever you decide to pull "`e1000_osdep.c`" (that doesn't sound like a whole driver) from will have been built for an entirely unrelated codebase, and unless we reuse an entire subsystem of an existing kernel, that makes no sense, as a "porting layer" would already far exceed such a simple driver.

**Comment by cleanbaja** [comment]
to be continued, in the form of a realtek driver (intel e1000 is too legacy for today's usecase)

**Pull request closed without merging**
