### PR TITLE
posix: Fix a duplicated bragi message ID

### PR DESCRIPTION
**Pull request by borrrden**
Between getpgid and setpgid

### CODE REVIEW

**Comment by avdgrinten** [comment]
We should only renumber the duplicated ID here and keep the remaining IDs.

**Comment by borrrden** [comment]
Interesting. I didn’t think it mattered since everything gets the updated number anyway but this means that either the numbers will no longer be in order in the file or getpgid and setpgid won’t appear next to each other in the list. Do you have a preference?

**Comment by avdgrinten** [comment]
AFAICS the messages are not numbered by IDs anyway. So we can keep the order but change the ID.

**Comment by borrrden** [comment]
Alright, this PR just got really tiny I love it 😄

**Comment by avdgrinten** [comment]
LGTM now, thanks!

**Pull request merged**
