### PR TITLE
meta: update supported hardware list in `README.md`

### PR DESCRIPTION
**Pull request by no92**

### CODE REVIEW

**Review by Dennisbonke — COMMENTED** [review]
LGTM, but can you also update the handbook? We list supported hardware at docs/src/getting-started/supported/index.md

**Comment by qookei** [comment]
Can you add XHCI to the USB controller list? :^)

**Comment by Dennisbonke** [comment]
> Can you add XHCI to the USB controller list? :^)

General: USB (UHCI, EHCI, XHCI) it's there :^)

**Comment by qookei** [comment]
Not in the README

**Comment by Dennisbonke** [comment]
> Not in the README

Whoops, in that case, please add :^)

**Comment by no92** [comment]
Updated as requested.

**Review by qookei — APPROVED** [review]

**Pull request merged**
