### PR TITLE
Implement shutting down the system from userspace

### PR DESCRIPTION
**Pull request by Dennisbonke**

### CODE REVIEW

**Review by no92 — APPROVED** [review]
LGTM

**Review by qookei — COMMENTED** [review]
NAK, we already have a way to power off from userspace: <https://github.com/managarm/managarm/blob/a8ebe4f48172982cc4f48dcd042a3d7494c4d313/drivers/libevbackend/src/libevbackend.cpp#L36-L83>

**Comment by qookei** [comment]
OFC this should still be done via posix-subsystem, so we can perform the appropriate permission checks, but adding a new system call is unnecessary.

**Comment by Dennisbonke** [comment]
> NAK, we already have a way to power off from userspace:
> 
> https://github.com/managarm/managarm/blob/a8ebe4f48172982cc4f48dcd042a3d7494c4d313/drivers/libevbackend/src/libevbackend.cpp#L36-L83

That seems to do a ACPI reset unconditionally, not an ACPI move to S5? So how would I adapt that?

**Comment by qookei** [comment]
IMO just add a sleep type enum and member to `PmResetRequest` to tell it what to do (suspend/shutdown/reboot) and update the libevbackend code to do a reboot.

**Comment by Dennisbonke** [comment]
Closed in favor of #724

**Pull request closed without merging**
