### PR TITLE
block/ahci: Various fixes

### PR DESCRIPTION
**Pull request by 64**
Fixes various AHCI issues to allow us to run on real hardware. Fixes managarm#323.

Draft until I can fix all the remaining problems.

### CODE REVIEW

**Comment by avdgrinten** [comment]
What is the status of this PR?

**Comment by 64** [comment]
When using queue depth 1, we hit the asynchronous nack issue which we believe to be an XHCI bug, but I’d be hesitant to merge until we've figured that out.

When using queue depth > 1 we hit some AHCI interface error (which may or may not be related to the XHCI issue).

**Comment by 64** [comment]
I've rebased this PR but we still have the same IRQ NACK issues, at least on my hardware (potentially still related to XHCI). Maybe someone else could test on a spare disk

**Comment by avdgrinten** [comment]
Does AHCI support MSIs? If yes, you could add MSI support to the driver (which should be only a few lines of code changes); this would isolate AHCI's IRQs from XHCI's.

**Comment by 64** [comment]
This PR should be mostly good to go, but there are some remaining issues:

1. `libarch` asserts that `alignof(commandTable) <= alignof(max_align_t)` [here](https://github.com/managarm/libarch/blob/923eb13477621d97503d1d2e8947801aa60ed6bf/include/arch/dma_structs.hpp#L329) which we deliberately break
2. https://github.com/managarm/managarm/issues/322 prevents booting in a lot of setups

Also I'm not sure if hardcoding MSI index 0 will be a problem in practice. I guess we'll have to see

**Comment by 64** [comment]
Okay, this is ready to merge now

**Review by avdgrinten — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
