### PR TITLE
Add GetMemoryInformation request to kerncfg/posix

### PR DESCRIPTION
**Pull request by Qwinci**

### CODE REVIEW

**Comment by avdgrinten** [comment]
Getting informative data from the kernel is better done by adding a `kerncfg` request. That way, we don't need to add a lot of additional syscalls, and it's easier to do access control and versioning.

**Comment by Qwinci** [comment]
I moved it to kerncfg like you suggested.

**Review by qookei — COMMENTED** [review]
Seems fine to me, although I'm unsure if this is the right time to start using separate response messages instead of adding fields to the `SvrResponse` message.

**Review by no92 — APPROVED** [review]
LGTM

**Review by ElectrodeYT — APPROVED** [review]
LGTM

**Review by Dennisbonke — APPROVED** [review]
LGTM

**Pull request merged**
