### PR TITLE
workflows: refactor urls post-migration

### PR DESCRIPTION
**Pull request by ArsenArsen**
secrets need updating still

### CODE REVIEW

**Comment by 64** [comment]
`docs/` needs updating too

**Comment by ArsenArsen** [comment]
`docs/`? that is the right module name:
```
[i] ~$ rsync-ssl rsync.managarm.org::
verify depth is 4
Welcome to our rsync server

buildenv        managarm build environment rsync root
wbuildenv       writeable managarm build environment rsync root
cbuildrt        cbuildrt directory rsync root
docs            managarm documentation rsync root
[i] ~$
```

**Comment by Dennisbonke** [comment]
I believe @64 was referring to the documentation folder in this repo, it has several places where it points to ci.managarm.org and pkgs.managarm.org, both of which no longer exist.

**Review by qookei — APPROVED** [review]
LGTM

**Pull request merged**
